import {NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'
import {Resend} from 'resend'
export const runtime='nodejs'
function pct(n,d){return d?Math.round(n/d*100):0}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function reportHtml({scopeLabel,stats,orgRows,courseRows}){return `<!doctype html><html lang="fr"><body style="margin:0;background:#f4f7fa;font-family:Arial,sans-serif;color:#172033"><div style="max-width:900px;margin:auto;padding:28px"><div style="background:#123b5d;color:white;padding:22px;border-radius:12px 12px 0 0"><div style="font-size:12px;letter-spacing:2px;opacity:.8">LMS IFAP · PILOTAGE HEBDOMADAIRE</div><h1 style="margin:8px 0 4px;font-size:25px">Tableau de bord</h1><div style="opacity:.85">${esc(scopeLabel)} · ${new Date().toLocaleDateString('fr-FR')}</div></div><div style="background:white;padding:22px;border:1px solid #e1e7ed"><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px">${[['Inscriptions',stats.enrollments],['Terminées',stats.completed],['Progression moyenne',stats.progress+' %'],['Présence',stats.attendance+' %'],['Réussite évaluations',stats.passRate+' %'],['Attestations',stats.certificates]].map(([l,v])=>`<div style="padding:15px;background:#f6f8fa;border-radius:9px"><div style="font-size:12px;color:#657486">${l}</div><div style="font-size:25px;font-weight:bold;margin-top:5px">${v}</div></div>`).join('')}</div><h2 style="font-size:18px;margin-top:28px">Activité par organisation</h2>${orgRows.length?`<table style="width:100%;border-collapse:collapse"><tr><th style="text-align:left;padding:8px;border-bottom:1px solid #ddd">Organisation</th><th>Inscrits</th><th>Terminés</th><th>Progression</th></tr>${orgRows.map(x=>`<tr><td style="padding:8px;border-bottom:1px solid #eee">${esc(x.name)}</td><td style="text-align:center">${x.enrollments}</td><td style="text-align:center">${x.completed}</td><td style="text-align:center">${x.progress}%</td></tr>`).join('')}</table>`:'<p>Aucune activité.</p>'}<h2 style="font-size:18px;margin-top:28px">Formations suivies</h2>${courseRows.length?`<table style="width:100%;border-collapse:collapse"><tr><th style="text-align:left;padding:8px;border-bottom:1px solid #ddd">Formation</th><th>Inscrits</th><th>Progression</th></tr>${courseRows.map(x=>`<tr><td style="padding:8px;border-bottom:1px solid #eee">${esc(x.title)}</td><td style="text-align:center">${x.enrollments}</td><td style="text-align:center">${x.progress}%</td></tr>`).join('')}</table>`:'<p>Aucune inscription.</p>'}</div><div style="padding:14px;color:#657486;font-size:11px">Rapport généré automatiquement par le LMS IFAP.</div></div></body></html>`}
export async function GET(req){
 const auth=req.headers.get('authorization')||'';const secret=process.env.CRON_SECRET||process.env.WEEKLY_REPORT_CRON_SECRET;if(secret&&auth!==`Bearer ${secret}`)return NextResponse.json({error:'Unauthorized'},{status:401})
 if(!process.env.SUPABASE_SERVICE_ROLE_KEY||!process.env.RESEND_API_KEY)return NextResponse.json({error:'Missing server configuration'},{status:500})
 const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});const resend=new Resend(process.env.RESEND_API_KEY)
 const {data:members,error:me}=await db.from('organization_members').select('organization_id,user_id,role,organizations(name)').in('role',['org_admin','platform_admin']);if(me)return NextResponse.json({error:me.message},{status:500})
 const {data:users,error:ue}=await db.auth.admin.listUsers({page:1,perPage:1000});if(ue)return NextResponse.json({error:ue.message},{status:500});const userMap=new Map((users.users||[]).map(u=>[u.id,u.email]).filter(x=>x[1]));const results=[]
 for(const member of (members||[])){const to=userMap.get(member.user_id);if(!to)continue;const orgId=member.role==='platform_admin'?null:member.organization_id
  let eq=db.from('enrollments').select('id,status,progress,learner_id,learners!inner(organization_id),deployments!inner(course_id,target_organization_id,courses!inner(title))');if(orgId)eq=eq.eq('learners.organization_id',orgId);const {data:e}=await eq;const enrollments=e||[]
  let sq=db.from('sessions').select('id,deployment_id,deployments!inner(target_organization_id),session_enrollments(enrollment_id),attendance(learner_id,present)');if(orgId)sq=sq.eq('deployments.target_organization_id',orgId);const {data:s}=await sq;const sessions=s||[]
  let cq=db.from('attestations').select('id,enrollment_id,enrollments!inner(learner_id,learners!inner(organization_id))');if(orgId)cq=cq.eq('enrollments.learners.organization_id',orgId);const {data:certs}=await cq
  const attendanceTotal=sessions.reduce((n,x)=>n+(x.session_enrollments?.length||0),0),attendancePresent=sessions.reduce((n,x)=>n+(x.attendance||[]).filter(a=>a.present).length,0)
  const evalsQuery=orgId?db.from('evaluation_attempts').select('passed,learner_id,learners!inner(organization_id)').eq('learners.organization_id',orgId):db.from('evaluation_attempts').select('passed');const {data:evals}=await evalsQuery
  const completed=enrollments.filter(x=>x.status==='completed'||Number(x.progress)>=100).length;const stats={enrollments:enrollments.length,completed,progress:enrollments.length?Math.round(enrollments.reduce((n,x)=>n+Number(x.progress||0),0)/enrollments.length):0,attendance:pct(attendancePresent,attendanceTotal),passRate:pct((evals||[]).filter(x=>x.passed).length,(evals||[]).length),certificates:(certs||[]).length}
  const om={};for(const x of enrollments){const k=String(x.learners?.organization_id||'');if(!om[k])om[k]={name:orgId?(member.organizations?.name||'Organisation'):'Organisation',enrollments:0,completed:0,progress:0};om[k].enrollments++;om[k].progress+=Number(x.progress||0);if(x.status==='completed'||Number(x.progress)>=100)om[k].completed++}const orgRows=Object.values(om).map(x=>({...x,progress:x.enrollments?Math.round(x.progress/x.enrollments):0}))
  const cm={};for(const x of enrollments){const c=x.deployments?.courses?.title||'Formation';const k=x.deployments?.course_id;if(!cm[k])cm[k]={title:c,enrollments:0,progress:0};cm[k].enrollments++;cm[k].progress+=Number(x.progress||0)}const courseRows=Object.values(cm).map(x=>({...x,progress:x.enrollments?Math.round(x.progress/x.enrollments):0})).sort((a,b)=>b.enrollments-a.enrollments).slice(0,10)
  const from=process.env.REPORT_FROM_EMAIL||'LMS IFAP <notifications@ifap.nc>';const {error}=await resend.emails.send({from,to:[to],subject:'LMS IFAP — tableau de bord hebdomadaire',html:reportHtml({scopeLabel:member.role==='platform_admin'?'Pilotage global':member.organizations?.name||'Votre organisation',stats,orgRows,courseRows})});results.push({email:to,ok:!error,error:error?.message||null})
 }
 return NextResponse.json({sent:results.length,results})
}
