'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import Shell from '../../components/Shell'
import {createClient} from '../../lib/supabase-browser'

export default function LearnerHome(){
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[learner,setLearner]=useState(null),[rows,setRows]=useState([]),[certs,setCerts]=useState([]),[catalog,setCatalog]=useState([])
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}
  const {data:l,error:le}=await s.from('learners').select('id,first_name,last_name,email,job_title,organization_id,organizations(name)').eq('user_id',user.id).eq('is_active',true).maybeSingle()
  if(le||!l){setError(le?.message||'Aucun profil apprenant associé à ce compte.');setLoading(false);return} setLearner(l)
  const {data:e,error:ee}=await s.from('enrollments').select('id,status,progress,started_at,completed_at,deployment_id,deployments(id,course_id,status,available_from,available_until,courses(id,title,description,duration_minutes,modality,thumbnail_path))').eq('learner_id',l.id).order('started_at',{ascending:false})
  const {data:cat,error:ce}=await s.from('courses').select('id,title,description,category,level,tags,featured,duration_minutes,modality').eq('visibility','ifap_catalog').eq('status','published').order('featured',{ascending:false}).order('updated_at',{ascending:false})
  const {data:a,error:ae}=await s.from('attestations').select('id,certificate_number,issued_at,revoked_at,pdf_path,enrollments!inner(learner_id,deployments(courses(title)))').eq('enrollments.learner_id',l.id).order('issued_at',{ascending:false})
  if(ee||ae||ce)setError((ee||ae||ce).message); setRows(e||[]);setCerts(a||[]);setCatalog(cat||[]);setLoading(false)
 })()},[])
 const stats=useMemo(()=>({active:rows.filter(r=>r.status!=='completed'&&Number(r.progress)<100).length,completed:rows.filter(r=>r.status==='completed'||Number(r.progress)>=100).length,avg:rows.length?Math.round(rows.reduce((a,r)=>a+Number(r.progress||0),0)/rows.length):0,certs:certs.filter(c=>!c.revoked_at).length}),[rows,certs])
 const next=rows.find(r=>r.status!=='completed'&&Number(r.progress)<100)
 const recommendations=useMemo(()=>{const enrolled=new Set(rows.map(r=>r.deployments?.course_id).filter(Boolean)); const activeCats=rows.map(r=>r.deployments?.courses?.category).filter(Boolean); const activeTags=rows.flatMap(r=>r.deployments?.courses?.tags||[]).map(x=>String(x).toLowerCase()); return catalog.filter(c=>!enrolled.has(c.id)).map(c=>{const tags=(c.tags||[]).map(x=>String(x).toLowerCase()); let score=(c.featured?3:0)+(activeCats.includes(c.category)?4:0)+tags.filter(t=>activeTags.includes(t)).length*2; return {...c,score}}).sort((a,b)=>b.score-a.score).slice(0,3)},[catalog,rows])
 return <Shell active="learner">
  <div className="learner-hero">
   <div><div className="eyebrow">MON ESPACE D'APPRENTISSAGE</div><h1>Bonjour {learner?.first_name||''} <span className="wave">👋</span></h1><p>Continuez votre parcours et développez vos compétences à votre rythme.</p></div>
   <div className="hero-avatar">{(learner?.first_name||'A').slice(0,1)}{(learner?.last_name||'').slice(0,1)}</div>
  </div>
  {error&&<div className="error">{error}</div>}
  {loading?<div className="card">Chargement de votre espace…</div>:<>
   <div className="learner-next card"><div className="next-copy"><span className="eyebrow">À REPRENDRE</span><h2>{next?.deployments?.courses?.title||'Votre parcours est à jour'}</h2><p>{next?'Poursuivez là où vous vous êtes arrêté.':'Découvrez vos prochaines formations dans le catalogue.'}</p>{next?<Link className="btn" href={`/learner/courses/${next.deployment_id}`}>Reprendre la formation <span>→</span></Link>:<Link className="btn" href="/catalog">Explorer les formations <span>→</span></Link>}</div><div className="next-progress"><div className="ring" style={{"--progress":next?Math.round(Number(next.progress||0)):100}}><span>{next?Math.round(Number(next.progress||0)):100}<small>%</small></span></div></div></div>
   <div className="grid learner-kpis modern-kpis"><Stat icon="↗" label="En cours" value={stats.active}/><Stat icon="✓" label="Terminées" value={stats.completed}/><Stat icon="◔" label="Progression" value={`${stats.avg}%`}/><Stat icon="◇" label="Attestations" value={stats.certs}/></div>
   <div className="section-title"><div><span className="eyebrow">VOTRE PARCOURS</span><h2>Mes formations</h2></div><Link className="text-link" href="/catalog">Voir le catalogue →</Link></div>
   {recommendations.length>0&&<><div className="section-title recommendation-title"><div><span className="eyebrow">POUR VOUS</span><h2>Continuez à développer vos compétences</h2><p className="muted">Des formations proposées selon votre parcours et vos centres d'intérêt.</p></div></div><div className="recommendation-grid">{recommendations.map((r,i)=><Link href={`/learner/catalog/${r.id}`} className="recommendation-card" key={r.id}><div className={`recommendation-art rec-${i}`}><span>{courseInitial(r.title)}</span><b>{r.featured?'À la une':'Suggestion'}</b></div><div><div className="course-meta">{r.category||'FORMATION'} {r.level?` · ${r.level}`:''}</div><h3>{r.title}</h3><p>{r.description||'Une compétence à développer pour la suite de votre parcours.'}</p><div className="recommendation-cta">Découvrir <span>→</span></div></div></Link>)}</div></>
   <div className="learner-course-grid">{rows.map(r=>{const c=r.deployments?.courses,p=Math.round(Number(r.progress||0));return <Link className="modern-course" href={`/learner/courses/${r.deployment_id}`} key={r.id}><div className="course-art"><span>{courseInitial(c?.title)}</span><i>{p>=100?'✓':'▶'}</i></div><div className="modern-course-body"><div className="course-meta">{c?.modality||'FORMATION'} {c?.duration_minutes?` · ${Math.round(c.duration_minutes/60*10)/10} h`:''}</div><h3>{c?.title||'Formation'}</h3><p>{c?.description||'Développez vos compétences avec votre parcours de formation.'}</p><div className="progress-line"><span style={{width:`${Math.min(100,p)}%`}}/></div><div className="course-footer"><span>{p>=100?'Formation terminée':'Progression'}</span><b>{p}%</b></div></div></Link>})}</div>
   {!rows.length&&<div className="empty card">Aucune formation ne vous est encore attribuée.</div>}
   <div className="grid2 learner-bottom"><div className="card modern-panel"><div className="section-head"><div><span className="eyebrow">RÉUSSITES</span><h2>Mes attestations</h2></div><Link className="text-link" href="/certificates">Tout voir →</Link></div>{certs.slice(0,3).map(c=><div className="certificate-modern" key={c.id}><div className="cert-icon">◇</div><div><b>{c.enrollments?.deployments?.courses?.title||'Attestation'}</b><span>{c.certificate_number||'Certificat'} · {new Date(c.issued_at).toLocaleDateString('fr-FR')}</span></div><span className="badge">{c.revoked_at?'Révoquée':'Validée'}</span></div>)}{!certs.length&&<div className="empty">Votre première attestation apparaîtra ici.</div>}</div><div className="card modern-panel profile-card"><span className="eyebrow">MON PROFIL</span><div className="profile-big"><div className="avatar large">{(learner?.first_name||'A').slice(0,1)}{(learner?.last_name||'').slice(0,1)}</div><div><h3>{learner?.first_name} {learner?.last_name}</h3><span>{learner?.job_title||'Apprenant'}</span></div></div><div className="profile-line"><span>Organisation</span><b>{learner?.organizations?.name||'—'}</b></div></div></div>
  </>}
 </Shell>
}
function Stat({icon,label,value}){return <div className="card modern-stat"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function courseInitial(t='Formation'){return t.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
